#!/usr/bin/env sh
# -*- mode: sh; sh-shell: sh; eval: (auto-fill-mode 1); -*-

echo "Sourcing battleprompt"

FILESDIR=${FILESDIR:-$HOME/src/repos/battleprompt}

[ -f $FILESDIR/term_colors ] && source $FILESDIR/term_colors

function git_prompt {
    FILESDIR=${FILESDIR:-$HOME/src/repos/battleprompt}
    [ -f $FILESDIR/git_prompt ] && {
        source "$FILESDIR/git_prompt"
    } || {
        echo "$FILEDIR not found"
    }
}

function regular_prompt {
    PS1="$Green$(a=`echo $VIRTUAL_ENV |rev|cut -f1 -d/ | rev` ; [ -n "$a" ] && echo venv:$a\  )"\
"${debian_chroot:+($debian_chroot)}$BGreen\u@\h\[\033[00m\]:$BBlue\w$BWhite \$$ColorOff "
}

unset FILESDIR
